spring:
  application:
    name: service-products
  datasource:
    url: jdbc:h2:mem:dbproduct
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: ${PORT:0} 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    